Add eggnog-mapper to annocomba --setup

diff --git a/annocomba b/annocomba
--- a/annocomba
+++ b/annocomba
@@ -75,7 +75,20 @@ if [[ $SETUP == "TRUE" ]]; then
 		echo "Error during MAKER setup."
 		exit 1
 	fi
-	if [[ $FUN == "done" && $MAK == "done" ]]; then
+	EGG=""
+	if [[ ! -d "data/eggnog_database/" ]]; then
+                mkdir data/eggnog_database
+        fi
+
+	if snakemake --use-singularity --singularity-args "-B $(pwd) " -p -r setup_eggnog --cores 1  ; then
+		echo "EGGNOG for annocomba setup complete."
+		EGG="done"
+	else
+		echo "Error during EGGNOG setup."
+		exit 1
+	fi
+
+	if [[ $FUN == "done" && $MAK == "done" && $EGG == "done" ]]; then
 		touch .annocomba_setup.done
 		exit 0
 	else
